# Generated by Django 4.2 on 2026-08-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': 'پست', 'verbose_name_plural': 'پستها'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='acitve',
            new_name='active',
        ),
    ]
