# Generated by Django 4.2 on 2026-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(choices=[('adult', 'adult'), ('teen', 'teen'), ('child', 'child')], default='adult', max_length=255),
        ),
    ]
