# Generated by Django 6.0 on 2026-08-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of product')),
                ('price', models.IntegerField(verbose_name='Price of product ')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Description for product')),
                ('rate', models.IntegerField(verbose_name='Rate from 0 to 5 ')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
