# Generated by Django 6.0 on 2026-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('laptop', 'laptop')], default='smartphone', max_length=30),
        ),
    ]
