# Generated by Django 6.0 on 2026-08-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('laptop', 'laptop'), ('Headphones & Buds', 'Headphones & Buds'), ('Gaming', 'Gaming')], default='smartphone', max_length=30),
        ),
    ]
