# Generated by Django 6.0 on 2026-08-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_category_options_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active (if quantity not zero)'),
        ),
    ]
