# Generated by Django 6.0 on 2026-08-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(verbose_name='Active (if quantity not zero)'),
        ),
    ]
