# Generated by Django 6.0 on 2026-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(choices=[('register', 'register-problem'), ('login', 'login-problem'), ('complain', 'complain')], max_length=10),
        ),
    ]
